services:
  mongo:
    image: mongo:latest
    container_name: mongo_users_web
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27018:27017'
    volumes:
      - ./mongo_data:/data/db
